# Generated by Django 3.2.8 on 2021-11-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211107_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена авто'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Брэнд авто'),
        ),
    ]
