# Generated by Django 3.2.8 on 2021-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211110_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Цена авто'),
        ),
    ]
